/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as NewRouteImport } from './routes/new'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as BlogIdIndexRouteImport } from './routes/blog.$id.index'
import { Route as BlogIdEditRouteImport } from './routes/blog.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdIndexRoute = BlogIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogIdRoute,
} as any)
const BlogIdEditRoute = BlogIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BlogIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/docs': typeof DocsRoute
  '/new': typeof NewRoute
  '/blog/$id': typeof BlogIdRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/blog/$id/edit': typeof BlogIdEditRoute
  '/blog/$id/': typeof BlogIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/docs': typeof DocsRoute
  '/new': typeof NewRoute
  '/blog': typeof BlogIndexRoute
  '/blog/$id/edit': typeof BlogIdEditRoute
  '/blog/$id': typeof BlogIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/docs': typeof DocsRoute
  '/new': typeof NewRoute
  '/blog/$id': typeof BlogIdRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/blog/$id/edit': typeof BlogIdEditRoute
  '/blog/$id/': typeof BlogIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/docs'
    | '/new'
    | '/blog/$id'
    | '/blog/'
    | '/blog/$id/edit'
    | '/blog/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/blogs' | '/docs' | '/new' | '/blog' | '/blog/$id/edit' | '/blog/$id'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/docs'
    | '/new'
    | '/blog/$id'
    | '/blog/'
    | '/blog/$id/edit'
    | '/blog/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRoute
  DocsRoute: typeof DocsRoute
  NewRoute: typeof NewRoute
  BlogIdRoute: typeof BlogIdRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id/': {
      id: '/blog/$id/'
      path: '/'
      fullPath: '/blog/$id/'
      preLoaderRoute: typeof BlogIdIndexRouteImport
      parentRoute: typeof BlogIdRoute
    }
    '/blog/$id/edit': {
      id: '/blog/$id/edit'
      path: '/edit'
      fullPath: '/blog/$id/edit'
      preLoaderRoute: typeof BlogIdEditRouteImport
      parentRoute: typeof BlogIdRoute
    }
  }
}

interface BlogIdRouteChildren {
  BlogIdEditRoute: typeof BlogIdEditRoute
  BlogIdIndexRoute: typeof BlogIdIndexRoute
}

const BlogIdRouteChildren: BlogIdRouteChildren = {
  BlogIdEditRoute: BlogIdEditRoute,
  BlogIdIndexRoute: BlogIdIndexRoute,
}

const BlogIdRouteWithChildren =
  BlogIdRoute._addFileChildren(BlogIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRoute,
  DocsRoute: DocsRoute,
  NewRoute: NewRoute,
  BlogIdRoute: BlogIdRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
